-- Air Quality Monitor v2.0 - Database Schema
-- Generated by Installation Wizard
-- 
-- This script creates the necessary database tables for the Air Quality Monitor system
-- Usage: Import this file to your MySQL/MariaDB database

-- Set charset and collation
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Create database (optional - uncomment if needed)
-- CREATE DATABASE IF NOT EXISTS `air_quality_monitor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE `air_quality_monitor`;

-- --------------------------------------------------------
-- Table structure for `air_monitor_settings`
-- Stores system configuration and user preferences
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `air_monitor_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `setting_value` text COLLATE utf8mb4_unicode_ci,
  `setting_type` enum('string','integer','boolean','json','array') COLLATE utf8mb4_unicode_ci DEFAULT 'string',
  `description` text COLLATE utf8mb4_unicode_ci,
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'general',
  `is_readonly` tinyint(1) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`),
  KEY `idx_category` (`category`),
  KEY `idx_readonly` (`is_readonly`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for `air_monitor_logs`
-- Stores system logs, API calls, and error messages
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `air_monitor_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `log_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `log_level` enum('debug','info','warning','error','critical') COLLATE utf8mb4_unicode_ci DEFAULT 'info',
  `message` text COLLATE utf8mb4_unicode_ci,
  `data` json DEFAULT NULL,
  `source` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_log_type` (`log_type`),
  KEY `idx_log_level` (`log_level`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_source` (`source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for `air_monitor_data`
-- Stores historical air quality data for analytics
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `air_monitor_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `aqi` int(11) DEFAULT NULL,
  `pm25` decimal(5,2) DEFAULT NULL,
  `pm10` decimal(5,2) DEFAULT NULL,
  `pm1` decimal(5,2) DEFAULT NULL,
  `temperature` int(11) DEFAULT NULL,
  `humidity` int(11) DEFAULT NULL,
  `pressure` int(11) DEFAULT NULL,
  `wind_speed` decimal(4,1) DEFAULT NULL,
  `source` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_url` text COLLATE utf8mb4_unicode_ci,
  `raw_data` json DEFAULT NULL,
  `location` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT 'Bangkok',
  `station_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_quality` enum('excellent','good','fair','poor') COLLATE utf8mb4_unicode_ci DEFAULT 'good',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_aqi` (`aqi`),
  KEY `idx_source` (`source`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_location` (`location`),
  KEY `idx_data_quality` (`data_quality`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for `air_monitor_users`
-- Stores admin users and session management
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `air_monitor_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `full_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('admin','viewer','editor') COLLATE utf8mb4_unicode_ci DEFAULT 'viewer',
  `is_active` tinyint(1) DEFAULT '1',
  `last_login` timestamp NULL DEFAULT NULL,
  `login_count` int(11) DEFAULT '0',
  `failed_attempts` int(11) DEFAULT '0',
  `lockout_until` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_role` (`role`),
  KEY `idx_active` (`is_active`),
  KEY `idx_last_login` (`last_login`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for `air_monitor_api_sources`
-- Stores API source configurations and their status
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `air_monitor_api_sources` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_type` enum('device_api','public_station','city_api','custom') COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_url` text COLLATE utf8mb4_unicode_ci,
  `priority` int(11) DEFAULT '1',
  `is_active` tinyint(1) DEFAULT '1',
  `config_data` json DEFAULT NULL,
  `last_success` timestamp NULL DEFAULT NULL,
  `last_error` text COLLATE utf8mb4_unicode_ci,
  `error_count` int(11) DEFAULT '0',
  `success_count` int(11) DEFAULT '0',
  `avg_response_time` decimal(6,3) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_source_type` (`source_type`),
  KEY `idx_priority` (`priority`),
  KEY `idx_active` (`is_active`),
  KEY `idx_last_success` (`last_success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Insert default settings
-- --------------------------------------------------------

INSERT INTO `air_monitor_settings` (`setting_key`, `setting_value`, `setting_type`, `description`, `category`) VALUES
('app_name', 'Air Quality Monitor v2.0', 'string', 'Application name displayed in headers', 'general'),
('app_version', '2.0', 'string', 'Current application version', 'general'),
('update_interval', '300', 'integer', 'Data refresh interval in seconds', 'api'),
('max_retries', '3', 'integer', 'Maximum API retry attempts', 'api'),
('timeout', '15', 'integer', 'API request timeout in seconds', 'api'),
('default_location', 'Bangkok', 'string', 'Default monitoring location', 'display'),
('theme_mode', 'device', 'string', 'Default theme (device/classic)', 'display'),
('language', 'th', 'string', 'Default language (th/en)', 'display'),
('debug_mode', 'false', 'boolean', 'Enable debug logging', 'system'),
('log_retention_days', '30', 'integer', 'Days to keep log entries', 'system'),
('data_retention_days', '365', 'integer', 'Days to keep air quality data', 'system'),
('enable_cache', 'true', 'boolean', 'Enable API response caching', 'performance'),
('cache_duration', '60', 'integer', 'Cache duration in seconds', 'performance'),
('admin_session_timeout', '3600', 'integer', 'Admin session timeout in seconds', 'security'),
('max_login_attempts', '5', 'integer', 'Maximum login attempts before lockout', 'security'),
('lockout_duration', '1800', 'integer', 'Account lockout duration in seconds', 'security');

-- --------------------------------------------------------
-- Insert default admin user (username: admin, password: sensor2025)
-- --------------------------------------------------------

INSERT INTO `air_monitor_users` (`username`, `password_hash`, `full_name`, `role`, `is_active`) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'System Administrator', 'admin', 1);

-- --------------------------------------------------------
-- Insert default API sources
-- --------------------------------------------------------

INSERT INTO `air_monitor_api_sources` (`source_name`, `source_type`, `source_url`, `priority`, `is_active`, `config_data`) VALUES
('Canvas 39 Device API', 'device_api', 'https://device.iqair.com/v2/6790850e7307e18fb3e0c815/validated-data', 1, 1, '{"timeout": 15, "retry_count": 3}'),
('Canvas 39 Public Station', 'public_station', 'https://www.iqair.com/thailand/bangkok/bangkok/canvas-39', 2, 1, '{"scraping_method": "dom", "selectors": {"aqi": ".aqi-value", "pm25": ".pm25-value"}}'),
('Bangkok City API', 'city_api', 'https://api.iqair.com/v2/city?city=Bangkok&state=Bangkok&country=Thailand&key=demo', 3, 1, '{"city": "Bangkok", "state": "Bangkok", "country": "Thailand"}');

-- --------------------------------------------------------
-- Create indexes for better performance
-- --------------------------------------------------------

-- Composite indexes for common queries
CREATE INDEX `idx_data_date_source` ON `air_monitor_data` (`created_at`, `source`);
CREATE INDEX `idx_logs_type_level` ON `air_monitor_logs` (`log_type`, `log_level`);
CREATE INDEX `idx_settings_category_key` ON `air_monitor_settings` (`category`, `setting_key`);

-- --------------------------------------------------------
-- Create views for common data queries
-- --------------------------------------------------------

-- Latest air quality data
CREATE OR REPLACE VIEW `latest_air_data` AS
SELECT 
    `aqi`,
    `pm25`,
    `pm10`,
    `pm1`,
    `temperature`,
    `humidity`,
    `pressure`,
    `wind_speed`,
    `source`,
    `location`,
    `created_at`
FROM `air_monitor_data`
WHERE `created_at` = (SELECT MAX(`created_at`) FROM `air_monitor_data`)
LIMIT 1;

-- API source status summary
CREATE OR REPLACE VIEW `api_source_status` AS
SELECT 
    `source_name`,
    `source_type`,
    `is_active`,
    `priority`,
    `last_success`,
    `error_count`,
    `success_count`,
    CASE 
        WHEN `success_count` = 0 THEN 0
        ELSE ROUND((`success_count` / (`success_count` + `error_count`)) * 100, 2)
    END as `success_rate`,
    `avg_response_time`
FROM `air_monitor_api_sources`
ORDER BY `priority`;

-- System health summary
CREATE OR REPLACE VIEW `system_health` AS
SELECT 
    (SELECT COUNT(*) FROM `air_monitor_api_sources` WHERE `is_active` = 1) as `active_sources`,
    (SELECT COUNT(*) FROM `air_monitor_logs` WHERE `log_level` = 'error' AND `created_at` > DATE_SUB(NOW(), INTERVAL 1 HOUR)) as `recent_errors`,
    (SELECT `created_at` FROM `air_monitor_data` ORDER BY `created_at` DESC LIMIT 1) as `last_data_update`,
    (SELECT COUNT(*) FROM `air_monitor_data` WHERE `created_at` > DATE_SUB(NOW(), INTERVAL 1 DAY)) as `data_points_today`;

-- --------------------------------------------------------
-- Set foreign key checks back to normal
-- --------------------------------------------------------

SET FOREIGN_KEY_CHECKS = 1;

-- --------------------------------------------------------
-- Completion message
-- --------------------------------------------------------

-- Installation completed successfully!
-- 
-- Default admin credentials:
-- Username: admin
-- Password: sensor2025
-- 
-- Remember to:
-- 1. Change the default admin password
-- 2. Configure your API sources in the admin panel
-- 3. Test all API endpoints
-- 4. Set up regular database maintenance
-- 
-- For support, refer to README.md